### ISSUE TITLE
Error in read.dcf(path) :  Found continuation line starting ' person("Jiangyu" ...' at begin of record

### ISSUE THREAD

**Issue by SongTastexyy** [jywang2016/rBAS#1]
成功执行了install.packages('devtools')，安装devtools成功后  ，再进行rBAS包的安装 ，执行命令devtools::install_github("jywang2016/rBAS")后出现以下error：
Error in read.dcf(path) :  Found continuation line starting ' person("Jiangyu" ...' at begin of record

**Comment by jywang2016** [comment]
Thanks for your feedback. There are some spaces in the person lines of DESCRIPTION file. I cut the spaces and fix the bug. Please try the installation again.
